### ISSUE TITLE
compile failed with setupbodyfont before starttext

### ISSUE THREAD

**Issue by walkthetalk** [contextgarden/luametatex#4]
! Math error: parameter 'supshiftup' with id 51 in style 2 is not set.

```
\setupbodyfont[14pt]

\starttext
\bTABLE
\bTABLEhead
\bTR
  \bTH  \m{f_c^{\ast}} \eTH
\eTR
\eTABLEhead
\eTABLE
\stoptext
```

**Comment by adityam** [comment]
It is better to use the [mailing list](https://wiki.contextgarden.net/Mailing_Lists) for questions related to ConTeXt (the macro package).
