### ISSUE TITLE
Fails to compile on HURD

### ISSUE THREAD

**Issue by hpreusse** [contextgarden/luametatex#9]
The file source/luarest/lmtfilelib.c fails to compile on GNU/Hurd b/c MAXPATHLEN is not defined there. The build log is visible [here](https://buildd.debian.org/status/fetch.php?pkg=luametatex&arch=hurd-i386&ver=2.10.08%2Bds-1&stamp=1691866622&raw=0). I tried to find an upstream repository for that piece of software, but did not find it.

**Comment by hanshagen** [comment]
I'll add this (you can add it and try yourself): 

    # ifdef MAXPATHLEN
        # define MY_MAXPATHLEN MAXPATHLEN
    # else 
        # define MY_MAXPATHLEN 255
    # endif

**Comment by hpreusse** [comment]
Yes, this is probably the most common way to solve the issue. I don't have a GNU/Hurd system at hand, I'll probably upload the latest release soon and then we'll know the results.

**Comment by hpreusse** [comment]
Works with v2.11.02.
